"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Workspaces = exports.Profile = exports.OAuth = exports.Envelopes = void 0;
var Envelopes_js_1 = require("./resources/Envelopes.js");
Object.defineProperty(exports, "Envelopes", { enumerable: true, get: function () { return Envelopes_js_1.Envelopes; } });
var OAuth_js_1 = require("./resources/OAuth.js");
Object.defineProperty(exports, "OAuth", { enumerable: true, get: function () { return OAuth_js_1.OAuth; } });
var Profile_js_1 = require("./resources/Profile.js");
Object.defineProperty(exports, "Profile", { enumerable: true, get: function () { return Profile_js_1.Profile; } });
var Workspaces_js_1 = require("./resources/Workspaces.js");
Object.defineProperty(exports, "Workspaces", { enumerable: true, get: function () { return Workspaces_js_1.Workspaces; } });
